---
title: "R Notebook"
output: html_notebook
---

Who had the longest long jump seen in the data?


```{r}
decathalon_second_clean %>% 
  select(long_jump, name) %>% 
  arrange(desc(long_jump)) %>% 
  slice_max(long_jump)
  
```


What was the average 100m time in each competition?

```{r}

decathalon_second_clean %>% 
  select(x100m, competition) %>% 
  group_by(competition) %>% 
  summarise(avg = mean(x100m))
  
```

Who had the highest total points across both competitions?

```{r}

decathalon_second_clean %>% 
  select(name, points) %>% 
  group_by(name) %>% 
  summarise(sum = sum(points)) %>% 
  slice_max(sum)
  
```

What was the shot-put scores for the top three competitors in each competition?

```{r}
decathalon_second_clean <-  decathalon_second_clean %>% 
  mutate(competition = as.character(competition))  # changes competition from factor to character
  
glimpse(decathalon_second_clean)
    
decathalon_second_clean %>%
  filter(competition == 'OlympicG') %>% 
  select(name, competition, shot_put) %>% 
  group_by(competition) %>% 
  arrange(desc(shot_put), by_group = TRUE) %>%   # top 3 for OlympicG competition
  top_n(3, shot_put)
  
  
  decathalon_second_clean %>%
  filter(competition == 'Decastar') %>% 
  select(name, competition, shot_put) %>% 
  group_by(competition) %>% 
  arrange(desc(shot_put), by_group = TRUE) %>%      # top 3 for Decastar competition
  top_n(3, shot_put) 



```

What was the average points for competitors who ran the 400m in less than 50 seconds vs. those than ran 400m in more than 50 seconds?


```{r}
decathalon_second_clean %>% 
  filter(x400m >= 50) %>% 
  summarise(average_points_slow = mean(points))

decathalon_second_clean %>% 
  filter(x400m <= 50) %>% 
  summarise(average_points_fast = mean(points))
  
```

